#!/usr/bin/env python

import sys
import typing

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from mpl_toolkits.mplot3d import Axes3D
from scipy.spatial.transform import Rotation


df = pd.read_csv(sys.argv[1])

df['v'] = np.sqrt(df['vel_x']**2 + df['vel_y']**2 + df['vel_z']**2)
df['a'] = np.sqrt(df['acc_x']**2 + df['acc_y']**2 + df['acc_z']**2)

x = df['pos_x']
y = df['pos_y']
z = df['pos_z']

fig = plt.figure(figsize=(16, 8))
gs = fig.add_gridspec(2, 2)
ax = typing.cast(Axes3D, fig.add_subplot(gs[:, 0], projection='3d'))
ax.plot(x, y, z)

max_range = max(
    x.max() - x.min(),
    y.max() - y.min(),
    z.max() - z.min()
) / 2

mid_x = (x.max() + x.min()) / 2
mid_y = (y.max() + y.min()) / 2
mid_z = (z.max() + z.min()) / 2

ax.set_xlim(mid_x - max_range, mid_x + max_range)
ax.set_ylim(mid_y - max_range, mid_y + max_range)
ax.set_zlim(mid_z - max_range, mid_z + max_range)
ax.set_xlabel('x (m)')
ax.set_ylabel('y (m)')
ax.set_zlabel('z (m)')
ax.set_title('Trajectory')

ax.scatter([0], [0], 0, color='red', marker='o')

ground_x, ground_y = np.meshgrid(
    np.linspace(mid_x - max_range, mid_x + max_range, 10),
    np.linspace(mid_y - max_range, mid_y + max_range, 10),
)
ground_z = np.full(ground_x.shape, 0.0)

ax.plot_surface(ground_x, ground_y, ground_z, color='black', alpha=0.5)

# add orientation vectors
q = df[['q_x', 'q_y', 'q_z', 'q_w']].values
rot = Rotation.from_quat(q)

body_vec = np.array([1, 0, 0])
dirs = rot.apply(body_vec) # Rotate into world frame - shape (N,3)

step = round(0.05 * max_range)
xs, ys, zs = x[::step], y[::step], z[::step]
us, vs, ws = dirs[::step].T

scale = round(0.05 * max_range)
ax.quiver(xs, ys, zs, us, vs, ws, length=scale, color='black', normalize=True)


# secondary plots
# ax2 = fig.add_subplot(gs[0, 1])
# ax2.plot(df['time'], df['vel_z'])
# ax2.axhline(0, color='black', linestyle='--')
# ax2.set_xlabel('time (s)')
# ax2.set_ylabel('z-velocity (m/s)')

ax2 = fig.add_subplot(gs[0, 1])
ax2.plot(df['time'], df['alpha_y'])
ax2.axhline(0, color='black', linestyle='--')
ax2.set_xlabel('time (s)')
ax2.set_ylabel('alpha_y (rad/s^2)')

# ax3 = fig.add_subplot(gs[1, 1])
# ax3.plot(df['time'], df['mach'])
# ax3.axhline(0, color='black', linestyle='--')
# ax3.set_xlabel('time (s)')
# ax3.set_ylabel('Mach')
ax3 = fig.add_subplot(gs[1, 1])
ax3.plot(df['time'], df['alpha'])
ax3.axhline(0, color='black', linestyle='--')
ax3.set_xlabel('time (s)')
ax3.set_ylabel('AoA (deg)')
ax3.set_ylim(-30, 30)

plt.tight_layout()
plt.subplots_adjust(wspace=0.2)
plt.show()

print(f'Apogee: {df['pos_z'].max()} m')
print(f'Max speed: {df['v'].max()} m/s')
print(f'Max mach: {df['mach'].max()} M')
